{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 79,
   "id": "a2c4059c-7b55-498c-addb-cb6da6f72879",
   "metadata": {},
   "outputs": [],
   "source": [
    "import pandas as pd\n",
    "import numpy as np\n",
    "import statsmodels.api as sm\n",
    "import matplotlib.pyplot as plt\n",
    "import seaborn as sns\n",
    "import statsmodels.formula.api as smf\n",
    "import re"
   ]
  },
  {
   "cell_type": "raw",
   "id": "f600e2e9-90b9-4a66-8150-14b5c781d9de",
   "metadata": {},
   "source": [
    "#Test data set\n",
    "test_df = pd.DataFrame({\n",
    "    \"ScanArea\": [\"test data frame\"] * 16,\n",
    "    \"TrackId\": [\"A\",\"A\",\"A\",\"A\",\n",
    "                \"B\",\"B\",\"B\",\"B\",\n",
    "                \"C\",\"C\",\"C\",\"C\",\n",
    "                \"D\",\"D\",\"D\",\"D\"],\n",
    "    \n",
    "    \"sheet_name\": [\n",
    "        \"Circularity\", \"Area (um2)\", \"TotalLength (um)\", \"LongestPath (um)\",\n",
    "        \"Circularity\", \"Area (um2)\", \"TotalLength (um)\", \"LongestPath (um)\",\n",
    "        \"Circularity\", \"Area (um2)\", \"TotalLength (um)\", \"LongestPath (um)\",\n",
    "        \"Circularity\", \"Area (um2)\", \"TotalLength (um)\", \"LongestPath (um)\"\n",
    "    ],\n",
    "\n",
    "    \"Repetition_0\": [0.99, 60, 20, 21, 0.97, 40, 30, 31, 0.99, 55, 20, 21, np.nan, np.nan, np.nan, np.nan],\n",
    "    \"Repetition_1\": [0.98, 70, 25, 26, 0.96, 160, 35, 36, 0.94, 85, 35, 36, np.nan, np.nan, np.nan, np.nan],\n",
    "    \"Repetition_2\": [0.94, 120, 30, 31, 0.95, 170, 40, 41, 0.90, 105, 45, 46, 0.96, 60, 30, 31],\n",
    "    \"Repetition_3\": [0.93, 130, 35, 36, 0.94, 190, 50, 51, 0.89, 115, 55, 56, 0.92, 125, 45, 46],\n",
    "    \"Repetition_4\": [0.93, 130, 45, 36, 0.94, 190, 50, 51, 0.89, 115, 55, 56, 0.92, 125, 45, 46],\n",
    "})"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 80,
   "id": "43bf866e-62ea-492c-a265-66ae7db0683e",
   "metadata": {},
   "outputs": [],
   "source": [
    "def combine_excel_sheets(file_path):\n",
    "    # Load Excel file\n",
    "    xls = pd.ExcelFile(file_path)\n",
    "    \n",
    "    # Get all sheet names\n",
    "    sheet_names = xls.sheet_names\n",
    "    \n",
    "    # Remove \"Job Configuration\" sheets (case-insensitive)\n",
    "    sheet_names = [\n",
    "        s for s in sheet_names\n",
    "        if \"job configuration\" not in s.lower()\n",
    "    ]\n",
    "    \n",
    "    all_data = []\n",
    "    \n",
    "    # Loop over each sheet\n",
    "    for sheet in sheet_names:\n",
    "        sheet_data = pd.read_excel(file_path, sheet_name=sheet)\n",
    "        \n",
    "        # Select relevant columns:\n",
    "        # - Exact columns: ScanArea, TrackId\n",
    "        # - Columns containing \"Repetition\"\n",
    "        repetition_cols = [col for col in sheet_data.columns if \"Repetition\" in col]\n",
    "        \n",
    "        selected_cols = [\"ScanArea\", \"TrackId\"] + repetition_cols\n",
    "        \n",
    "        # Keep only columns that actually exist (avoids errors)\n",
    "        selected_cols = [col for col in selected_cols if col in sheet_data.columns]\n",
    "        \n",
    "        sheet_data_filtered = sheet_data[selected_cols].copy()\n",
    "        \n",
    "        # Add sheet name column\n",
    "        sheet_data_filtered[\"sheet_name\"] = sheet\n",
    "        \n",
    "        # Reorder columns (like dplyr::select)\n",
    "        cols = [\"ScanArea\", \"TrackId\", \"sheet_name\"] + [\n",
    "            col for col in sheet_data_filtered.columns\n",
    "            if col not in [\"ScanArea\", \"TrackId\", \"sheet_name\"]\n",
    "        ]\n",
    "        sheet_data_filtered = sheet_data_filtered[cols]\n",
    "        \n",
    "        # Append to list\n",
    "        all_data.append(sheet_data_filtered)\n",
    "    \n",
    "    # Combine all sheets into one DataFrame\n",
    "    combined_data = pd.concat(all_data, ignore_index=True)\n",
    "    \n",
    "    return combined_data"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 81,
   "id": "b73a72a2-bd51-42bb-aaa0-48a6104b28fd",
   "metadata": {},
   "outputs": [],
   "source": [
    "#In the data frame \"Repetition X\" doesn't correspond to the actual time \n",
    "#For further analysis it Repetition X must correspond to time \n",
    "#This function changes time frame to match my time parameters:\n",
    "#imaged every 4 hours for the first 20 hours and then imaged every 2 for the next 76\n",
    "def rename_repetition_columns(df: pd.DataFrame) -> pd.DataFrame:\n",
    "    #Start time at 0 hours\n",
    "    current_time = 0\n",
    "    \n",
    "    new_columns = []\n",
    "    #Loop over all Repetition Columns\n",
    "    for col_name in df.columns:\n",
    "        #Check if column starts with \"Repetition\"\n",
    "        if col_name.startswith(\"Repetition\"):\n",
    "            #new column name with the current time\n",
    "            new_col_name = f\"Repetition {current_time}\"\n",
    "            new_columns.append(new_col_name)\n",
    "\n",
    "            #change the time: first 20 hours are 4 hours apart, the rest are 2 hours apart\n",
    "            if current_time < 20:\n",
    "                current_time += 4\n",
    "            else:\n",
    "                current_time += 2\n",
    "        else:\n",
    "            #keep non Repetition names\n",
    "            new_columns.append(col_name)\n",
    "\n",
    "    df.columns = new_columns\n",
    "    return df"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "1aa16121-b467-44ad-a159-22efe1d463fe",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": 82,
   "id": "61232740-53cb-409c-b918-a880746eadaf",
   "metadata": {},
   "outputs": [],
   "source": [
    "#In the data frame \"Repetition X\" doesn't correspond to the actual time \n",
    "#For further analysis it Repetition X must correspond to time \n",
    "#This function changes time frame to match my time parameters:\n",
    "#imaged every hour\n",
    "def rename_repetition_columns2(df: pd.DataFrame) -> pd.DataFrame:\n",
    "    #Start time at 0 hours\n",
    "    current_time = 0\n",
    "    \n",
    "    new_columns = []\n",
    "    #Loop over all \"Repetition\" Columns\n",
    "    for col_name in df.columns:\n",
    "        #Check if column starts with \"Repetition\"\n",
    "        if col_name.startswith(\"Repetition\"):\n",
    "            #new column name with the current time\n",
    "            new_col_name = f\"Repetition {current_time}\"\n",
    "            new_columns.append(new_col_name)\n",
    "\n",
    "            #change the time: first 20 hours are 4 hours apart, the rest are 2 hours apart\n",
    "            if current_time < 20:\n",
    "                current_time += 1\n",
    "            else:\n",
    "                current_time += 1\n",
    "        else:\n",
    "            #keep non Repetition names\n",
    "            new_columns.append(col_name)\n",
    "\n",
    "    df.columns = new_columns\n",
    "    return df"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 83,
   "id": "13a6c310-3512-41a9-aa98-1a3b50c9d194",
   "metadata": {},
   "outputs": [],
   "source": [
    "#In the data frame \"Repetition X\" doesn't correspond to the actual time \n",
    "#For further analysis it Repetition X must correspond to time \n",
    "#This function changes time frame to match my time parameters:\n",
    "#imaged every other hour\n",
    "def rename_repetition_columns3(df: pd.DataFrame) -> pd.DataFrame:\n",
    "    #Start time at 0 hours\n",
    "    current_time = 0\n",
    "    \n",
    "    new_columns = []\n",
    "    #Loop over all Repetition Columns\n",
    "    for col_name in df.columns:\n",
    "        #Check if column starts with \"Repetition\"\n",
    "        if col_name.startswith(\"Repetition\"):\n",
    "            #new column name with the current time\n",
    "            new_col_name = f\"Repetition {current_time}\"\n",
    "            new_columns.append(new_col_name)\n",
    "\n",
    "            #change the time: first 20 hours are 4 hours apart, the rest are 2 hours apart\n",
    "            if current_time < 20:\n",
    "                current_time += 2\n",
    "            else:\n",
    "                current_time += 2\n",
    "        else:\n",
    "            #keep non Repetition names\n",
    "            new_columns.append(col_name)\n",
    "\n",
    "    df.columns = new_columns\n",
    "    return df"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 84,
   "id": "9cb793d9-a550-4893-8fcb-4c01c2dba964",
   "metadata": {},
   "outputs": [],
   "source": [
    "#determine the extent of istropic growth \n",
    "#imput must be include:\n",
    "#oCelloScope data frame that is transformed to have data type to be saved under coulumn \"sheet_name\" and Repetition number corresponds to hour of experiment\n",
    "#oCelloScope data must also have \"TrackId\" \n",
    "#species, media, and date must also be str. its important for final data sets\n",
    "\n",
    "#return: isotropic_growth[1] or isotropic_growth[data] is a data frame\n",
    "#return: isotropic_growth[2] or isotropic_growth[plot] is a plot showing segmenteted regression\n",
    "\n",
    "def isotropic_growth(df, species, media, date):\n",
    "\n",
    "    # Find repetition columns\n",
    "    time_columns = [col for col in df.columns if \"Repetition\" in col]\n",
    "\n",
    "    # Pivot to long format\n",
    "    data_long = df.melt(\n",
    "        id_vars=[col for col in df.columns if col not in time_columns],\n",
    "        value_vars=time_columns,\n",
    "        var_name=\"time\",\n",
    "        value_name=\"value\"\n",
    "    )\n",
    "\n",
    "    # Convert repetition column names to numeric time\n",
    "    data_long[\"time\"] = (\n",
    "        data_long[\"time\"]\n",
    "        .str.replace(r\"[^0-9.]\", \"\", regex=True)\n",
    "        .astype(float)\n",
    "    )\n",
    "\n",
    "    # Filter for area data only\n",
    "    area_data = data_long[data_long[\"sheet_name\"] == \"Area (um2)\"].copy()\n",
    "\n",
    "    # Remove ungerminated conidia\n",
    "    # Keep only conidia that grew to at least 2.5x their original size\n",
    "    area_data[\"Original_Size\"] = area_data.groupby(\"TrackId\")[\"value\"].transform(\"first\")\n",
    "    area_data[\"Max_Size\"] = area_data.groupby(\"TrackId\")[\"value\"].transform(\"max\")\n",
    "    \n",
    "    \n",
    "    #filter only area data\n",
    "    area_data_filtered = area_data[\n",
    "        area_data[\"Max_Size\"] > 2.5 * area_data[\"Original_Size\"]\n",
    "    ].copy()\n",
    "\n",
    "    #stall code if no area over no 2.5X (look at original video to confirm germination)\n",
    "    if area_data_filtered.empty:\n",
    "        raise ValueError(\"No rows remain after filtering for growth > 2.5x original size.\")\n",
    "\n",
    "    # Prepare data for segmented regression by removing excess data\n",
    "    model_df = area_data_filtered[[\"time\", \"value\"]].dropna().copy()\n",
    "\n",
    "    #confirm there is enough time period points to make an accurate segmented regression \n",
    "    if len(model_df) < 4:\n",
    "        raise ValueError(\"Not enough data points for segmented regression.\")\n",
    "\n",
    "    #confirm only individual data points and individual conidia are viewed\n",
    "    unique_times = np.sort(model_df[\"time\"].unique())\n",
    "\n",
    "    #list of potential breakpoints\n",
    "    candidate_breaks = unique_times[1:-1]\n",
    "\n",
    "    #name initial values\n",
    "    best_break = None\n",
    "    best_model = None\n",
    "    best_rss = np.inf\n",
    "\n",
    "    # Piecewise linear model with one breakpoint:\n",
    "    # y = b0 + b1*time + b2*max(0, time - breakpoint)\n",
    "    for bp in candidate_breaks:\n",
    "        x = model_df[\"time\"].values\n",
    "        hinge = np.maximum(0, x - bp)\n",
    "\n",
    "        X = pd.DataFrame({\n",
    "            \"intercept\": 1.0,\n",
    "            \"time\": x,\n",
    "            \"hinge\": hinge\n",
    "        })\n",
    "\n",
    "        fit = sm.OLS(model_df[\"value\"].values, X).fit()\n",
    "        rss = np.sum(fit.resid ** 2)\n",
    "        \n",
    "        #looping through and confirmining best fit for all possible timepoints\n",
    "        if rss < best_rss:\n",
    "            best_rss = rss\n",
    "            best_break = bp\n",
    "            best_model = fit\n",
    "    \n",
    "    #pullout best fit breakpoint\n",
    "    breakpoints = np.array([best_break])\n",
    "\n",
    "    # Predicted area at breakpoint using model deirved above\n",
    "    bp_X = pd.DataFrame({\n",
    "        \"intercept\": [1.0],\n",
    "        \"time\": [best_break],\n",
    "        \"hinge\": [0.0]\n",
    "    })\n",
    "    breakpoint_values = best_model.predict(bp_X).values\n",
    "\n",
    "    #Pull inital area of conidia at first recorded time\n",
    "    first_recording_time = area_data_filtered[\"time\"].min()\n",
    "    first_area = area_data_filtered.loc[\n",
    "        area_data_filtered[\"time\"] == first_recording_time, \"value\"\n",
    "    ].mean()\n",
    "\n",
    "    # Results dataframe of all conidia\n",
    "    breakpoint_results = pd.DataFrame({\n",
    "        \"Species\": [species],\n",
    "        \"Media\": [media],\n",
    "        \"Date\": [date],\n",
    "        \"Breakpoint_Time\": [breakpoints[0]],\n",
    "        \"Breakpoint_Area\": [breakpoint_values[0]],\n",
    "        \"Average_First_Area\": [first_area],\n",
    "        #Simple fold change\n",
    "        \"Swelling_change\": [breakpoint_values[0] / first_area]\n",
    "    })\n",
    "\n",
    "    #Add predictions for visualization\n",
    "    #pull time values\n",
    "    x_all = area_data_filtered[\"time\"].values\n",
    "\n",
    "    #derive hinge point (breakpoint) in model\n",
    "    hinge_all = np.maximum(0, x_all - best_break)\n",
    "\n",
    "    pred_X = pd.DataFrame({\n",
    "        \"intercept\": 1.0,\n",
    "        \"time\": x_all,\n",
    "        \"hinge\": hinge_all\n",
    "    })\n",
    "\n",
    "    model_data = area_data_filtered.copy()\n",
    "    model_data[\"predicted\"] = best_model.predict(pred_X)\n",
    "\n",
    "    # Create figure and axis\n",
    "    fig, ax = plt.subplots(figsize=(8, 6))\n",
    "\n",
    "    sns.scatterplot(data=model_data, x=\"time\", y=\"value\", ax=ax)\n",
    "    sns.lineplot(data=model_data.sort_values(\"time\"), x=\"time\", y=\"predicted\", ax=ax)\n",
    "\n",
    "    ax.axvline(x=best_break, linestyle=\"--\")\n",
    "    ax.set_title(f\"Segmented Regression with Breakpoints and Values - {species}\")\n",
    "    ax.set_xlabel(\"Time (Hours)\")\n",
    "    ax.set_ylabel(\"Area (μm²)\")\n",
    "\n",
    "    plt.tight_layout()\n",
    "\n",
    "    return {\n",
    "        \"data\": breakpoint_results,\n",
    "        \"plot\": fig\n",
    "    }"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 85,
   "id": "6da3f3d2-6ecd-4bb5-a876-a65cbf4c258e",
   "metadata": {},
   "outputs": [],
   "source": [
    "def find_time_point(df, breakpoint_value, species, media, date):\n",
    "    # Get time point columns containing \"Repetition\"\n",
    "    time_cols = [col for col in df.columns if \"Repetition\" in col]\n",
    "\n",
    "    # Unique TrackIds\n",
    "    track_ids = pd.unique(df[\"TrackId\"])\n",
    "\n",
    "    # Initialize output lists\n",
    "    selected_time_points = [np.nan] * len(track_ids)\n",
    "    last_time_points = [np.nan] * len(track_ids)\n",
    "    selected_lengths = [np.nan] * len(track_ids)\n",
    "    final_lengths = [np.nan] * len(track_ids)\n",
    "\n",
    "    confirm_n = 3\n",
    "\n",
    "    # Loop through each TrackId\n",
    "    for i, track_id in enumerate(track_ids):\n",
    "        track_data = df[df[\"TrackId\"] == track_id]\n",
    "\n",
    "        # Separate Circularity, Area, and TotalLength data\n",
    "        circularity_data = track_data[track_data[\"sheet_name\"] == \"Circularity\"]\n",
    "        area_data = track_data[track_data[\"sheet_name\"] == \"Area (um2)\"]\n",
    "        length_data = track_data[track_data[\"sheet_name\"] == \"TotalLength (um)\"]\n",
    "\n",
    "        # Skip if any required sheet is missing\n",
    "        if circularity_data.empty or area_data.empty or length_data.empty:\n",
    "            continue\n",
    "\n",
    "        # Use first row if multiple rows exist for a TrackId/sheet_name combination\n",
    "        circularity_row = circularity_data[time_cols].iloc[0]\n",
    "        area_row = area_data[time_cols].iloc[0]\n",
    "        length_row = length_data[time_cols].iloc[0]\n",
    "\n",
    "        # Find first valid initial area: non-NA and between 10 and 75\n",
    "        initial_area = np.nan\n",
    "        for val in area_row:\n",
    "            if pd.notna(val) and 10 <= val <= 75:\n",
    "                initial_area = val\n",
    "                break\n",
    "\n",
    "        # This variable exists in your R code but is not used later\n",
    "        initial_circle = np.nan\n",
    "        for val in circularity_row:\n",
    "            if pd.notna(val) and val < 0.92:\n",
    "                initial_circle = val\n",
    "                break\n",
    "\n",
    "        # Find germination time point\n",
    "        if pd.notna(initial_area):\n",
    "            for j, col in enumerate(time_cols):\n",
    "                current_circularity = circularity_row[col]\n",
    "                current_area = area_row[col]\n",
    "\n",
    "                if pd.notna(current_circularity) and pd.notna(current_area):\n",
    "                    if current_circularity < 0.94 and current_area >= (breakpoint_value * initial_area * 1.25):\n",
    "                        L = len(time_cols)\n",
    "                        confirmed = False\n",
    "\n",
    "                        if j + confirm_n < L:\n",
    "                            confirmed = True\n",
    "                            for k in range(j + 1, j + confirm_n + 1):\n",
    "                                next_circ = circularity_row[time_cols[k]]\n",
    "                                next_area = area_row[time_cols[k]]\n",
    "\n",
    "                                if (\n",
    "                                    pd.isna(next_circ)\n",
    "                                    or pd.isna(next_area)\n",
    "                                    or not (\n",
    "                                        next_circ < 0.94\n",
    "                                        and next_area >= (breakpoint_value * initial_area * 1.25)\n",
    "                                    )\n",
    "                                ):\n",
    "                                    confirmed = False\n",
    "                                    break\n",
    "                        else:\n",
    "                            # Accept when fewer than confirm_n future frames exist\n",
    "                            confirmed = True\n",
    "\n",
    "                        if not confirmed:\n",
    "                            continue\n",
    "\n",
    "                        selected_time_points[i] = col\n",
    "                        selected_lengths[i] = length_row[col]\n",
    "                        break\n",
    "\n",
    "        # Find last non-NA length and corresponding time point\n",
    "        final_length_found = np.nan\n",
    "        for col in time_cols:\n",
    "            if pd.notna(length_row[col]):\n",
    "                final_length_found = length_row[col]\n",
    "                last_time_points[i] = col\n",
    "\n",
    "        final_lengths[i] = final_length_found\n",
    "\n",
    "    # Helper to extract numeric part from strings like \"Repetition 12\"\n",
    "    def extract_numeric(value):\n",
    "        if pd.isna(value):\n",
    "            return np.nan\n",
    "        nums = re.sub(r\"[^0-9.]\", \"\", str(value))\n",
    "        return float(nums) if nums else np.nan\n",
    "\n",
    "    # Build ScanArea map per TrackId\n",
    "    scanarea_map = (\n",
    "        df[[\"TrackId\", \"ScanArea\"]]\n",
    "        .drop_duplicates(subset=[\"TrackId\"])\n",
    "        .set_index(\"TrackId\")[\"ScanArea\"]\n",
    "    )\n",
    "\n",
    "    result = pd.DataFrame({\n",
    "        \"ScanArea\": [scanarea_map.get(track_id, np.nan) for track_id in track_ids],\n",
    "        \"TrackId\": track_ids,\n",
    "        \"selected_time_point\": [extract_numeric(x) for x in selected_time_points],\n",
    "        \"selected_time_point_word\": selected_time_points,\n",
    "        \"last_time_point\": [extract_numeric(x) for x in last_time_points],\n",
    "        \"selected_length\": selected_lengths,\n",
    "        \"final_length\": final_lengths,\n",
    "    }).drop_duplicates()\n",
    "\n",
    "    # Add metadata and growth rates\n",
    "    result[\"Species\"] = species\n",
    "    result[\"Media\"] = media\n",
    "    result[\"Date\"] = date\n",
    "\n",
    "    result[\"linear_growth_rate\"] = (\n",
    "        (result[\"final_length\"] - result[\"selected_length\"]) /\n",
    "        (result[\"last_time_point\"] - result[\"selected_time_point\"])\n",
    "    )\n",
    "\n",
    "    result[\"exponential_growth_rate\"] = (\n",
    "        (np.log(result[\"final_length\"]) - np.log(result[\"selected_length\"])) /\n",
    "        (result[\"last_time_point\"] - result[\"selected_time_point\"])\n",
    "    )\n",
    "\n",
    "    # Reorder columns to match the R output\n",
    "    result = result[\n",
    "        [\n",
    "            \"Species\",\n",
    "            \"Media\",\n",
    "            \"Date\",\n",
    "            \"ScanArea\",\n",
    "            \"TrackId\",\n",
    "            \"selected_time_point\",\n",
    "            \"selected_time_point_word\",\n",
    "            \"last_time_point\",\n",
    "            \"selected_length\",\n",
    "            \"final_length\",\n",
    "            \"linear_growth_rate\",\n",
    "            \"exponential_growth_rate\",\n",
    "        ]\n",
    "    ]\n",
    "\n",
    "    return result"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 86,
   "id": "97dd7163-2d58-4f51-a0dc-8382d3487a5d",
   "metadata": {},
   "outputs": [],
   "source": [
    "def length_post_germination(df, germination_results, species, media, date):\n",
    "    species_name = species\n",
    "    media_type = media\n",
    "    date_of_experiment = date\n",
    "\n",
    "    # Get time columns\n",
    "    time_cols = [col for col in df.columns if \"Repetition\" in col]\n",
    "\n",
    "    # Extract numeric time values from column names\n",
    "    def extract_time(col):\n",
    "        m = re.search(r\"([0-9]+\\.?[0-9]*)\", str(col))\n",
    "        return float(m.group(1)) if m else np.nan\n",
    "\n",
    "    time_intervals = np.array([extract_time(col) for col in time_cols], dtype=float)\n",
    "\n",
    "    # Filter for TotalLength data and merge with germination results\n",
    "    df_germinated = (\n",
    "        df[df[\"sheet_name\"] == \"TotalLength (um)\"]\n",
    "        .merge(germination_results, on=\"TrackId\", how=\"inner\")\n",
    "        .copy()\n",
    "    )\n",
    "\n",
    "    relative_time_data_list = []\n",
    "\n",
    "    # Loop through each germinated row\n",
    "    for _, row in df_germinated.iterrows():\n",
    "        track_id = row[\"TrackId\"]\n",
    "        germination_time_point = row[\"selected_time_point_word\"]\n",
    "\n",
    "        sample_data = df[\n",
    "            (df[\"TrackId\"] == track_id) &\n",
    "            (df[\"sheet_name\"] == \"TotalLength (um)\")\n",
    "        ]\n",
    "\n",
    "        if sample_data.empty:\n",
    "            continue\n",
    "\n",
    "        # Take first matching row\n",
    "        sample_row = sample_data.iloc[0]\n",
    "\n",
    "        length_values = pd.to_numeric(sample_row[time_cols], errors=\"coerce\").to_numpy()\n",
    "\n",
    "        if np.all(np.isnan(length_values)):\n",
    "            continue\n",
    "\n",
    "        # Find germination index\n",
    "        if germination_time_point not in time_cols:\n",
    "            continue\n",
    "\n",
    "        germination_index = time_cols.index(germination_time_point)\n",
    "\n",
    "        if germination_index >= len(length_values):\n",
    "            continue\n",
    "\n",
    "        relative_times = time_intervals - time_intervals[germination_index]\n",
    "\n",
    "        relative_time_data = pd.DataFrame({\n",
    "            \"track_id\": track_id,\n",
    "            \"relative_time\": relative_times,\n",
    "            \"length\": length_values\n",
    "        })\n",
    "\n",
    "        relative_time_data_list.append(relative_time_data)\n",
    "\n",
    "    # Combine all samples\n",
    "    if relative_time_data_list:\n",
    "        relative_time_data_combined = pd.concat(relative_time_data_list, ignore_index=True)\n",
    "    else:\n",
    "        relative_time_data_combined = pd.DataFrame(columns=[\"track_id\", \"relative_time\", \"length\"])\n",
    "\n",
    "    # Remove missing lengths\n",
    "    relative_time_data_combined = relative_time_data_combined.dropna(subset=[\"length\"]).copy()\n",
    "\n",
    "    # Median summary\n",
    "    if not relative_time_data_combined.empty:\n",
    "        total_length_median = (\n",
    "            relative_time_data_combined\n",
    "            .groupby(\"relative_time\", as_index=False)\n",
    "            .agg(\n",
    "                Median_Length=(\"length\", \"median\"),\n",
    "                n=(\"length\", \"count\")\n",
    "            )\n",
    "        )\n",
    "        total_length_median[\"log_Median_Length\"] = np.log(total_length_median[\"Median_Length\"])\n",
    "        total_length_median[\"Species\"] = species_name\n",
    "        total_length_median[\"Media\"] = media_type\n",
    "        total_length_median[\"Date\"] = date_of_experiment\n",
    "    else:\n",
    "        total_length_median = pd.DataFrame(\n",
    "            columns=[\n",
    "                \"relative_time\", \"Median_Length\", \"log_Median_Length\",\n",
    "                \"n\", \"Species\", \"Media\", \"Date\"\n",
    "            ]\n",
    "        )\n",
    "\n",
    "    # Linear model on 0 <= relative_time <= 24\n",
    "    fit_subset = total_length_median[\n",
    "        (total_length_median[\"relative_time\"] >= 0) &\n",
    "        (total_length_median[\"relative_time\"] <= 24)\n",
    "    ].copy()\n",
    "\n",
    "    total_length_median[\"lm_predicted\"] = np.nan\n",
    "    total_length_median[\"exm_predicted\"] = np.nan\n",
    "\n",
    "    if len(fit_subset) >= 2:\n",
    "        # Linear model\n",
    "        lm_model = smf.ols(\"Median_Length ~ relative_time\", data=fit_subset).fit()\n",
    "        total_length_median[\"lm_predicted\"] = lm_model.predict(total_length_median)\n",
    "\n",
    "        # Exponential model via log transform\n",
    "        exm_subset = fit_subset[fit_subset[\"Median_Length\"] > 0].copy()\n",
    "        if len(exm_subset) >= 2:\n",
    "            exm_model = smf.ols(\"log_Median_Length ~ relative_time\", data=exm_subset).fit()\n",
    "            total_length_median[\"exm_predicted\"] = np.exp(exm_model.predict(total_length_median))\n",
    "\n",
    "    # y-axis limit\n",
    "    valid_window = relative_time_data_combined[\n",
    "        (relative_time_data_combined[\"relative_time\"] >= 0) &\n",
    "        (relative_time_data_combined[\"relative_time\"] <= 24)\n",
    "    ]\n",
    "\n",
    "    if not valid_window.empty:\n",
    "        y_limit = valid_window[\"length\"].max() + 10\n",
    "    else:\n",
    "        y_limit = None\n",
    "\n",
    "    # Plot\n",
    "    fig, ax = plt.subplots(figsize=(10, 6))\n",
    "\n",
    "    # Individual conidia lines\n",
    "    if not relative_time_data_combined.empty:\n",
    "        for track_id, group in relative_time_data_combined.groupby(\"track_id\"):\n",
    "            group = group.sort_values(\"relative_time\")\n",
    "            ax.plot(\n",
    "                group[\"relative_time\"],\n",
    "                group[\"length\"],\n",
    "                color=\"black\",\n",
    "                alpha=0.7,\n",
    "                linewidth=1\n",
    "            )\n",
    "            ax.scatter(\n",
    "                group[\"relative_time\"],\n",
    "                group[\"length\"],\n",
    "                color=\"black\",\n",
    "                s=15,\n",
    "                alpha=0.7\n",
    "            )\n",
    "\n",
    "    # Median line\n",
    "    if not total_length_median.empty:\n",
    "        ax.plot(\n",
    "            total_length_median[\"relative_time\"],\n",
    "            total_length_median[\"Median_Length\"],\n",
    "            linewidth=2,\n",
    "            label=\"Median Length\"\n",
    "        )\n",
    "\n",
    "    # Linear model\n",
    "    if \"lm_predicted\" in total_length_median.columns and total_length_median[\"lm_predicted\"].notna().any():\n",
    "        ax.plot(\n",
    "            total_length_median[\"relative_time\"],\n",
    "            total_length_median[\"lm_predicted\"],\n",
    "            linewidth=2,\n",
    "            label=\"Linear Growth Model\"\n",
    "        )\n",
    "\n",
    "    # Exponential model\n",
    "    if \"exm_predicted\" in total_length_median.columns and total_length_median[\"exm_predicted\"].notna().any():\n",
    "        ax.plot(\n",
    "            total_length_median[\"relative_time\"],\n",
    "            total_length_median[\"exm_predicted\"],\n",
    "            linewidth=2,\n",
    "            label=\"Exponential Growth Model\"\n",
    "        )\n",
    "\n",
    "    ax.set_title(\"Length Over Time Post-Germination (Germination Time = 0)\")\n",
    "    ax.set_xlabel(\"Relative Time since Germination (Hours)\")\n",
    "    ax.set_ylabel(\"Length (µm)\")\n",
    "    ax.set_xlim(0, 24)\n",
    "    if y_limit is not None:\n",
    "        ax.set_ylim(0, y_limit)\n",
    "    ax.legend()\n",
    "    ax.grid(True, alpha=0.3)\n",
    "\n",
    "    return {\n",
    "        \"relative_time_df\": relative_time_data_combined,\n",
    "        \"median_length_df\": total_length_median,\n",
    "        \"plot\": fig\n",
    "    }"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
